### ISSUE TITLE
Uploading badge returns in 404 error

### ISSUE THREAD

**Issue by kai-nguyen-aligent** [aligent/nx-serverless-deploy-pipe#19]
After switching step size to `2x` in the pipeline, we start experiencing the following errors:

```bash
ℹ Running command: npx nx run-many -t deploy -- --stage stg --aws-profile bitbucket-deployer 
.......
 NX   Successfully ran target deploy for 5 projects
✖ AxiosError: Request failed with status code 404
```

The only changes that we made:

![Bitbucket pipeline diff](https://github.com/user-attachments/assets/bbc4e0ad-1ad3-4a76-8af9-df5bde8dcdb7)

Please note that this issue only happens if we set `UPLOAD_BADGE` to `true`.

**Comment by kai-nguyen-aligent** [comment]
Update: I now experience this issue again in another project that use the old pipeline settings:
```yaml
definitions:
  services:
    docker:
      memory: 3072
steps:
  ...
   - step: &push-serverless
        name: 🚀 Deploy Service
        script:
          - pipe: docker://aligent/nx-serverless-deploy-pipe:20
            ...
```

This now seems to be something has changed from Bitbucket side.
